### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by Drewsapple** [Leathong/openscad-support-vscode#10]
When I switch `launchPath` to org.openscad.OpenSCAD, preview launches panic with "Gtk-WARNING cannot open display".

I don't know vscode extention development, but I think using spawn instead of execFile [here](https://github.com/Leathong/openscad-support-vscode/blob/b5d49f92a44cba2b99cbc34cf84b2df66e133b58/src/preview.ts#L50) would allow the `DISPLAY=:0` env-var. 

VSCode may or may not be running with it, if it is, you could just pass process.env, otherwise it would be nice if I could specify env-vars to the openscad executable via preferences.

**Comment by Leathong** [comment]
Thanks for feedback, I will try this. But I have no Linux test environment, I am not sure it will work.

**Comment by Leathong** [comment]
Have updated to 1.2.4, you can try it.
