### ISSUE TITLE
Message: clang-format: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by noppej** [Leathong/openscad-support-vscode#16]
I am running on OSX (Apple M1), with the latest versions of VSCode and OpenSCAD. 

When I try to save even an very simple file, I get the following:
```
  Message: clang-format: No such file or directory (os error 2)
  Code: -32603 
```

Is there a special setting I need for OSX to provide clang-format?

**Comment by Leathong** [comment]
It should be that you have enabled formatting on save, and clang-format is not installed or clang-format path is not set to the extension correctly.

**Comment by Leathong** [comment]
You can install clang-format by `brew install clang-format`
