### ISSUE TITLE
Add Saved/Modified/Flagged Sidebar

### ISSUE THREAD

**Issue by njsokalski** [Leathong/openscad-support-vscode#18]
In Visual Studio, there was an option to display (next to the line numbers) marks indicating whether the line had been saved, modified, and/or flagged. I found this very useful, since knowing what I had changed since last saving was very useful. I often keep OpenSCAD open so I can see the preview while I work on my code in VSCode, so I think it would be extremely useful with OpenSCAD, since I am constantly changing & saving stuff. I also recognize that flags are stored in a separate metadata file, so I realize that may not be possible, but if it is, it would be a nice addition.

**Comment by DeflateAwning** [comment]
This is way, way outside the scope of this plugin. If you track your projects in the Git version control, then you get this sort of feature natively. Maybe that's even what you're remembering?

**Comment by Leathong** [comment]
If you don't want to use VCS(like git), you can try local history. 
https://stackoverflow.com/questions/46446901/how-can-i-see-local-history-changes-in-visual-studio-code
