### ISSUE TITLE
Keyboard trigger for autocomplete?

### ISSUE THREAD

**Issue by akavlie** [Leathong/openscad-support-vscode#19]
I love the detailed autocomplete of object & operator names with the documentation that pops up to the right.
But as soon as you type the parenthesis, it disappears.
Is there a keyboard shortcut to trigger that to pop up again?

**Comment by Leathong** [comment]
cmd + i on MacOS

**Comment by Leathong** [comment]
You can put the mouse over the function in which you want to display the document. @akavlie
