### ISSUE TITLE
Almost no intellisense in modules with parameters

### ISSUE THREAD

**Issue by TTSKarlsson** [Leathong/openscad-support-vscode#2]
There's almost no intellisense in modules with parameters.

Example without parameters (Working):
![20220514_135832_229x282](https://user-images.githubusercontent.com/9962943/168424696-40a0b169-375d-42ee-ac88-a11e1df1bc7d.png)

Example with one parameter (Can only see the 2 globals and the parameter, but no modules or functions):
![20220514_135948_306x203](https://user-images.githubusercontent.com/9962943/168424739-a27f1f4d-47c0-4b67-93e9-1b1f875f22a2.png)

Example with two parameters (Like with one parameter, but can also not see the second parameter):
![20220514_140213_307x189](https://user-images.githubusercontent.com/9962943/168424807-8933799c-d7da-442d-a756-f8288bbaa7e8.png)

**Expected result would be to autocomplete builtin modules like cube and cylinder and so.**

**The actual result is that it doesn't autocomplete any builtins, custom modules or custom functions if the module has at least one parameter.**

Full example with the globals:
![20220514_140805_377x150](https://user-images.githubusercontent.com/9962943/168425008-a8714bdd-6e0d-41d6-b908-89a8439ab8b8.png)

Windows 11
VSCode version 1.67.1
Extension version 1.1.1
OpenSCAD version 2021.01

**Comment by Leathong** [comment]
Thanks for the feedback, I will check it.

**Comment by Leathong** [comment]
@TTSKarlsson A little bug, already fixed it. Just update to the 1.1.2 later.

**Comment by TTSKarlsson** [comment]
Amazing, works fine! Thanks <3
