### ISSUE TITLE
assert() used in a conditional variable assignment flagged as an error.

### ISSUE THREAD

**Issue by LenStruttmann** [Leathong/openscad-support-vscode#29]
OpenSCAD allows the following, even though it may not be exactly correct syntax .

Using an assert() call within a conditional assignment is flagged as a "missing identifier" error in vscode:

A = 1;
B = 2;
C = A<B? 10 : assert(false);
                                          | missing identifier

The code works as intended, i.e., if A<B, C is assigned value of 10,  if A>B, the assert is raised.

The workaround is to put some value, any value, after the assert(), e.g.,

C = A<B? 10 : assert(false) 11;

...even though that value will never be assigned as the operation is preempted by the assert().

**Comment by Leathong** [comment]
This usage is too strange; there should be an expression that can be evaluated after the colon. Perhaps it would be more reasonable to use “assert” on its own, e.g. assert(A<B).

**Comment by LenStruttmann** [comment]
I guess that, strictly, it should be:

A = 1;
B = 2;
assert(A<B, "Bad things happened, A is less than B");
C = A<B? 10 : "don't care";

For me,  that is awkward and prone to error since you need to specify exactly the same logic test for both the assert() and the conditional assignment.

However, that's kinda not the point of my submission.  OpenSCAD currently correctly processes the easily understood code that I originally posted. It is misleading (and somewhat annoying) to me that vscode flags it as an error, including painting the filename red in the outline pane.

Admittedly, this is a minor thing.  Thanks.

**Comment by Leathong** [comment]
I think you don’t need to write 
`C = A<B? 10 : “don’t care”; `
just writing 
`C = 10 `
would suffice, as the assert will error out if the condition is not met, making the additional check redundant.
