### ISSUE TITLE
Inner module is not getting completions for outer module's parameters

### ISSUE THREAD

**Issue by mjparme** [Leathong/openscad-support-vscode#3]
The parameters of an outer module are in scope in an inner module. However, no completion is being offered for the parameters of the outer module in the inner module.

```
module main(parameter1 = 10) {

    module innerModuleInMain() {
        par<would expect completion for parameter1 to appear here>
    }
}
```
<img width="597" alt="Screen Shot 2022-07-25 at 4 10 03 PM" src="https://user-images.githubusercontent.com/1580996/180877366-f95f8840-e810-41e5-a580-19fbf2ad8475.png">

**Comment by Leathong** [comment]
Indeed it is, I will check it.

**Comment by Leathong** [comment]
update to v1.2.1.

**Comment by mjparme** [comment]
@Leathong thanks! works great!
