### ISSUE TITLE
Module completion with default parameter values

### ISSUE THREAD

**Issue by mjparme** [Leathong/openscad-support-vscode#4]
It would be nice if the module completion would include any default parameters and their values. Currently the completion popup shows the default values and their values but when you select it for completion it doesn't actually include the parameters. This isn't very useful because if I want to change the defaults I then have copy/paste the module definition rendering the completion functionality worthless (this is especially troublesome if the module is defined in an included file).

Parameters are shown in the completion popup:

<img width="596" alt="Screen Shot 2022-07-25 at 4 41 21 PM" src="https://user-images.githubusercontent.com/1580996/180878773-2d3b64a2-b9ae-43a8-b6a2-fb7fd50fe761.png">

However, after selecting main from the popup the parameters aren't there:

<img width="608" alt="Screen Shot 2022-07-25 at 4 41 31 PM" src="https://user-images.githubusercontent.com/1580996/180878785-5dc9d7a8-20fc-43be-aade-6477011fc437.png">

**Comment by Leathong** [comment]
I will consider add a config, so that you can select the completion behavior.

**Comment by Leathong** [comment]
update to v1.2.1.

**Comment by mjparme** [comment]
@Leathong thanks! this one has already made things tons easier!
