### ISSUE TITLE
The listed feature of path completion doesn't work (no completion is offered)

### ISSUE THREAD

**Issue by mjparme** [Leathong/openscad-support-vscode#5]
I have attached a gif to demonstrate the problem. In the gif I am typing in `main.scad` and trying to complete `includedFile.scad` which is located in the same directory as `main.scad`:

![noPathCompletion](https://user-images.githubusercontent.com/1580996/180880809-12b582dd-68da-49b9-ae5a-92dde48128bf.gif)

Interestingly, path validation works i.e. if I type something like `include <junk.scad>` it will correctly hightlight it red because it doesn't exist. Likewise if I manually type out `include <includedFile.scad>` it properly sees that it exists and I can complete modules/variables found in that file.

**Comment by Leathong** [comment]
What platform are you on? I main work on Mac，so the Mac platform is the most fully tested.

**Comment by mjparme** [comment]
> What platform are you on? I main work on Mac，so the Mac platform is the most fully tested.

@Leathong I am currently running MacOS Monterey 12.4

**Comment by Leathong** [comment]
That work well for me, maybe the vscode did not send a request to server. You can temporarily disable other OpenSCAD extensions and try again, or just press 'cmd + i' to trigger suggestion.

**Comment by Leathong** [comment]
@mjparme  I reproduce the issue. The parser does not recognize the include statement because of missing '>'. You can select 'include' suggestion to complete the whole include statement  for now.

**Comment by mjparme** [comment]
@Leathong when I select the `include` suggestion I end up with this `include <include <PATH>`

`cmd + i` does trigger a suggestion popup but `includedFile.scad` isn't in the list.

**Comment by Leathong** [comment]
@mjparme I mean you can select `include` suggestion when you type `inc`, not after 'include <', or just type whole `include <>`，`cmd + i` not list files because the parser did't recognize 'include <' as an include statement.

**Comment by mjparme** [comment]
@Leathong Ahh ok, I get it now. That workaround indeed works:

![completion](https://user-images.githubusercontent.com/1580996/181277619-05d9a01b-176d-49d3-8b42-fc60a6e8d40a.gif)

**Comment by Leathong** [comment]
I will fix these issues on weekends.

**Comment by Leathong** [comment]
update to v1.2.1.
