### ISSUE TITLE
"each" keyword is not recognized

### ISSUE THREAD

**Issue by WizardUli** [Leathong/openscad-support-vscode#7]
![image](https://user-images.githubusercontent.com/3875278/192113121-f0357473-64fa-4391-a3ff-e31cc4f86e54.png)

`each` is a valid openscad construct akin to `*` in python but currently is highlighted as a syntax error by this extension.

**Comment by Leathong** [comment]
I have created a PR to [tree-sitter-openscad](https://github.com/bollian/tree-sitter-openscad/pull/7). I will update the extension after the PR is accepted.

**Comment by Leathong** [comment]
update to 1.2.2
