### ISSUE TITLE
Assertions in function is not recognized.

### ISSUE THREAD

**Issue by hsuenaga** [Leathong/openscad-support-vscode#8]
# Abstract
assert() statement is allowed to use with function definitions as same as let() statement. But openscad-support-vscode reports syntax error.

# How to Reproduce
Try following code.
```
function test(x) = assert(x > 0) x;
echo (test(0));
```
OpenSCAD recognizes assert and reports failure.
```
ERROR: Assertion '(x > 0)' failed in file Test.scad, line 1
TRACE: called by 'test' in file Test.scad, line 2
TRACE: called by 'echo' in file Test.scad, line 2
Geometries in cache: 1
Geometry cache size in bytes: 0
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Total rendering time: 0:00:00.000
Current top level object is empty.
```

# Confirmed versions
- openscad-support-vscode
  - v1.2.2(2022-07-29)
- OpenSCAD
  - OpenSCAD version 2021.01

# Reference
[https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Other_Language_Features](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Other_Language_Features)

**Comment by Leathong** [comment]
"assert" can be everywhere, even break an expression, I have no idea to parse it now.

**Comment by Leathong** [comment]
May be should treat it as a comment.

**Comment by hsuenaga** [comment]
Thanks!! It seems good idea to treat assert() as a kind of comment. It's enough for most users. 

Truly, it acts as a comment if we write correct code. :-p

**Comment by Leathong** [comment]
update to 1.2.3
